guillevidal/GesSalud

- README.md
Estamos testeando que las protecciones de la rama que aplicamos estén funcionando
> chore:testeando el git branch strategy

- client/src/App.js
- client/src/components/initialPys/initial.jsx
- client/src/components/initialPys/initialPys.scss
Se agrego el componente de la vista inicial de Pys (posteriormente se haran modificaciones de estilo) el componente responde a la siguiente ruta localhost:3000/initialPys.
> componente inicial de PyS

- client/src/App.js
- client/src/components/forms/CreateSpecialist/CreateSpecialist.jsx
- client/src/components/forms/CreateSpecialist/CreateSpecialist.scss
- client/src/components/forms/Person/Person.jsx
funcionalidad de inputs en el formulario para crear especialista
> actualización funcionalidad formulario crear especialista

- .gitignore
- api/index.js
- api/src/models/tipo_especialidad.js
Cargando las especialidades en la base de datos , para terminar las relaciones del especialista
> Cargando las especialidades en la base de datos

- client/src/components/forms/CreateSpecialist/CreateSpecialist.jsx
- client/src/components/forms/Person/Person.jsx
inputs de formulario para crear especialista, datos personales, tipos de especialidades, y identificación profesional
> completos campos de input para creacion de especialista

- client/src/components/forms/CreatePatient/CreatePatient.jsx
- client/src/components/forms/CreateSpecialist/CreateSpecialist.jsx
- client/src/components/forms/Person/Person.jsx
ajustes a formulario creacion de especialista y actualización inputs formulario paciente
> actualizacion formulario paciente

- client/src/components/forms/CreateSpecialist/CreateSpecialist.jsx
se ajustan los inputs para crear correctamente un especialista desde el formulario, llega al backend el especialista creado
> inputs finalizados para crear especialista

- client/src/App.js
- client/src/components/forms/Person/Person.jsx
- client/src/components/homeRH/Card.jsx
- client/src/components/homeRH/EditSpecialty/EditSpecialty.jsx
se crea vista para modificar especialista, cambio de ruta del componente en App y en la Card de especialista
> vista_modificar_especialista

- client/src/components/forms/CreatePatient/CreatePatient.jsx
- client/src/components/homeRH/EditSpecialty/EditSpecialty.jsx
- client/src/components/initialPys/patientManagement/PatientEdit/PatientEdit.jsx
- client/src/components/initialPys/patientManagement/initial/patietCardDetails.jsx
actualizaciones al componente de modificar paciente, links a los componentes de modificar paciente y especialista
> actualizaciones al componente modificar paciente

- client/src/components/forms/CreateSpecialist/CreateSpecialist.jsx
- client/src/components/forms/Person/Person.jsx
- client/src/components/initialPys/SpecialtyManagement/CreateAgenda/CreateAgenda.jsx
- client/src/components/initialPys/SpecialtyManagement/CreateAgenda/CreateAgenda.scss
- client/src/components/initialPys/SpecialtyManagement/Initial/InitialSpecialty.jsx
- client/src/components/initialPys/SpecialtyManagement/Initial/InitialSpecialty.scss
Se agrega componente de vista principal para la gestión de la agenda, componente de creación y consultas
> gestion_de_agenda

- client/src/components/initialPys/SpecialtyManagement/EditAgenda/TurnosAgendaCard.jsx
ajuste de funciones enlazadas generando error en renderizado
> ajuste de acciones en vista de agenda

- client/src/components/initialPys/SpecialtyManagement/CreateAgenda/CreateAgenda.jsx
generación de agendas múltiples
> creacion de agendas multiples

- client/src/App.js
- client/src/components/Landing/Landing.jsx
- client/src/components/Landing/RegistroPatient.jsx
- client/src/components/initialPys/TurnoManagement/SearchTurno.jsx
- client/src/components/initialPys/TurnoManagement/turnosCard.jsx
Se agrego la posibilidad de registrarse como paciente desde el landing, se espera hablar con los chicos del back ya que es necesario un token para el registro del paciente si no se ha logueado en sistema"
> Posibilidad de registro desde landing (Por resolver conflicto con token)

- client/src/components/initialPys/SpecialtyManagement/CreateAgenda/CreateAgenda.jsx
posibilidad de crear agenda para un día específico incluyendo sábados  o domingos
> crear agenda para un día incluido sabado o domingo

- api/src/routes/paciente.js
Fix ruta paciente endpoint /consulta/dni
> Frontend consulta DNI request

- client/src/App.js
- client/src/components/Landing/Landing.scss
- client/src/components/Landing/NotFound.jsx
- client/src/components/Landing/RegistroPatient.jsx
- client/src/components/forms/CreatePatient/CreatePatient.scss
- client/src/components/homeRH/HomeRH.jsx
- client/src/components/homeRH/SearchAmin.jsx
- client/src/components/initialPys/TurnoManagement/InicialTurno.scss
- client/src/components/specialist/ProfileSpecialist.jsx
- client/src/components/specialist/ProfileSpecialist.scss
- client/src/reducer/index.js
> Se agrega *Page not found*, se corrigen mensajes al usuario y se agregan estilos en general

- client/src/actions/index.js
Reverts guillevidal/GesSalud#305
> Revert "correccion action upload"

- client/src/components/Modal/ModalHistoriaClínica.js
- client/src/components/specialist/HomeSpecialist.jsx
- client/src/components/specialist/MisTurnosCard.jsx
Fix para eliminar turno desde la vista del paciente, generación de modal para visualizar historia clínica desde la vista de paciente
> fix para eliminar turno desde la vista de paciente

- client/src/components/specialist/HomeSpecialist.jsx
fix en vista de especialista, renderizado
> fix vista especialista médico

- client/src/components/specialist/HomeSpecialist.jsx
modal de historia clínica desde la vista del paciente
> modal historia clínica en vista de paciente

- client/src/components/Modal/Modal.scss
- client/src/components/Modal/ModalHistoriaClinica.js
- client/src/components/specialist/HomeSpecialist.jsx
- client/src/components/specialist/HomeSpecialist.scss
generación de pdf de historia clínica en vista de paciente
> generación de pdf historia clinica

- client/src/components/initialPys/patientManagement/initial/patientCardDetails.scss
- client/src/components/initialPys/patientManagement/initial/patietCardDetails.jsx
- client/src/components/specialist/HomeSpecialist.jsx
cambio de renderizado de historia clinica desde la vista de PYS, detalle de paciente
> cambio vista de historia clinica desde vista PyS

- client/src/components/Landing/RegistroPatient.jsx
- client/src/components/forms/CreatePatient/CreatePatient.jsx
- client/src/components/forms/CreatePys/CreatePys.jsx
- client/src/components/forms/CreateRRHH/CreateRRHH.jsx
- client/src/components/forms/CreateSpecialist/CreateSpecialist.jsx
- client/src/components/forms/Person/Person.jsx
validaciones de longitud en dni y phone
> validacion en formularios para dni y telefono
